-- Per-TEAM, per-bot monthly COST — the Postgres twin of the sqlite migration
-- 0043_bot_cost_per_team. Hand-written additive (like 0027/0028/0029), idempotent.
-- Data migration (the legacy backfill): packages/pro/migrations-pg/0019_bot_cost_to_classification.sql.
--
-- `cost_monthly_cents` is INTEGER in BOTH dialects on purpose: `numeric` has no sqlite twin AND
-- node-postgres returns it as a STRING, which would silently break the shared `number` wire type,
-- while REAL/double is a float64 that cannot hold money exactly. The WIRE unit is DOLLARS;
-- storage is cents, converted only at the store boundary. integer↔integer is what makes
-- schema-parity.test.ts pass.
--
-- NULLABLE WITH NO DEFAULT: NULL = "no cost opinion at this key" → inherit the team-0 row; 0 =
-- "explicitly free here" and must BEAT an inherited price. Hence `??`, never `||`. Existing rows
-- all land at NULL = today's behaviour exactly.
--
-- ⚠ Cost resolves FIELD-WISE while the rest of the row resolves ROW-WISE (an explicit team row
-- wins wholesale for the classification). See the sqlite twin for the full rationale and for the
-- paired write-path trap: a new team row must SEED `role` but must NOT seed the cost.
--
-- No backfill here: the legacy values sit in the PLUGIN-owned `pro_settings.bot_cost_json`, which
-- does not exist on an OSS install. See plugin migration 0019.
ALTER TABLE "bot_review_classification" ADD COLUMN IF NOT EXISTS "cost_monthly_cents" integer;
