import { PRODUCT_NAME } from '@pierre-review/shared';
import type { AiFixPushResult } from '@pierre-review/shared';
import type { ApplyAndPushTarget } from '../../pro/contract.js';
import type { AgentContext } from '../../review/agent-context.js';
import { getFixPrContext, getViewerCanPush } from './pr-context.js';
import { getFixById, markFixPushed } from './persist.js';

// PUSH A FINISHED FIX, AS-IS — the ONE path the Push button (routes.ts) and the AUTOMATIC push
// (auto-push.ts) share. Never a force push: onto the PR's own head branch (refused with HEAD_MOVED
// when that branch moved since the fix was generated) or onto a NEW branch with a PR opened against
// the base. No trunk step before it. `applyAndPush` settles the PR after the write.

export type PushFixOutcome =
  | { ok: true; result: AiFixPushResult }
  | {
      ok: false;
      // not_found / not_pushable / no_write / head_unavailable / branch_required / HEAD_MOVED /
      // PUSH_DENIED / APPLY_FAILED / failed
      code:
        | 'not_found'
        | 'not_pushable'
        | 'no_write'
        | 'head_unavailable'
        | 'branch_required'
        | 'HEAD_MOVED'
        | 'PUSH_DENIED'
        | 'APPLY_FAILED'
        | 'failed';
      message: string;
    };

export async function pushFix(
  ctx: AgentContext,
  input: { accountId: number; fixId: number; target: 'existing' | 'new'; branch?: string },
): Promise<PushFixOutcome> {
  const { accountId, fixId } = input;
  const row = await getFixById(ctx, accountId, fixId);
  if (!row) return { ok: false, code: 'not_found', message: 'Fix not found.' };
  if (row.status !== 'succeeded' || !row.patch || !row.baseSha)
    return { ok: false, code: 'not_pushable', message: 'This fix has nothing to push.' };

  const pr = await getFixPrContext(ctx, accountId, row.prId);
  if (!pr) return { ok: false, code: 'not_found', message: 'Pull request not found.' };

  if (!(await getViewerCanPush(ctx, accountId, pr.repoId)))
    return { ok: false, code: 'no_write', message: 'You cannot push to this repository.' };

  const commitMessage = row.commitMessage ?? 'AI fix';

  let target: ApplyAndPushTarget;
  if (input.target === 'existing') {
    const head = await ctx.github.fetchPrHeadInfo(accountId, pr.owner, pr.name, pr.number).catch(() => null);
    if (!head) return { ok: false, code: 'head_unavailable', message: 'Could not read the PR branch.' };
    target = { kind: 'existing', headRef: head.headRef };
  } else {
    const branch = (input.branch ?? '').trim();
    if (!branch) return { ok: false, code: 'branch_required', message: 'Name the new branch.' };
    // This body lands on GitHub, where it is read by people who have never seen this app — so it
    // names the PRODUCT, not the npm package. Nothing detects on this string.
    const prBody = `${row.summary ?? ''}\n\n---\nAutomated fix for #${pr.number}, generated by ${PRODUCT_NAME} AI Fix.`;
    target = {
      kind: 'new',
      branch,
      base: pr.baseRefName ?? pr.defaultBranch ?? 'main',
      title: commitMessage,
      body: prBody,
    };
  }

  try {
    const result = await ctx.coding.applyAndPush({
      accountId,
      owner: pr.owner,
      name: pr.name,
      prNumber: pr.number,
      baseSha: row.baseSha,
      patch: row.patch,
      commitMessage,
      target,
    });
    await markFixPushed(ctx, fixId, {
      pushedBranch: result.pushedBranch,
      pushedPrNumber: result.prNumber,
      pushedPrUrl: result.prUrl,
    });
    return { ok: true, result };
  } catch (err) {
    const code = (err as { code?: string })?.code;
    const message = err instanceof Error ? err.message : String(err);
    if (code === 'HEAD_MOVED' || code === 'PUSH_DENIED' || code === 'APPLY_FAILED') return { ok: false, code, message };
    ctx.log.warn({ err }, 'ai-fix push failed');
    return { ok: false, code: 'failed', message };
  }
}
