// WS1b — review-body / comment fingerprint engine (CORE, deterministic, NO AI).
//
// Given a review body + its inline-comment bodies (both are ALWAYS persisted, both
// modes — see the lean-storage note in CLAUDE.md), decide whether the text carries an
// automated-reviewer marker and, if so, which tool. This is one of the hard signals the
// layered classifier (reviewer-classify.ts) resolves on. It is purely a curated
// regex/token set — extend `FINGERPRINTS` (branded, vendor-specific) or the generic
// section (in-house AI tools that copy a severity taxonomy but carry no brand marker).
//
// Correctness contract (pinned by review-fingerprint.test.ts):
//   • Pierre's own posted-review marker `<!-- pierre:claude-review` → tool 'pierre'.
//   • a branded vendor marker → that vendor's ReviewBotKind.
//   • generic AI markers / a uniform severity taxonomy across ≥2 comments → 'in_house'.
//   • a plain human review body → { marked: false, tool: null, markers: [] }.
//
// `import type` only from shared (the backend never imports the shared VALUE at runtime).
import type { AutomatedReviewerKind } from '@pierre-review/shared';

export interface ReviewFingerprint {
  marked: boolean;
  tool: AutomatedReviewerKind | null;
  markers: string[];
}

interface FingerprintDef {
  kind: AutomatedReviewerKind;
  // A human-readable name per pattern (parallel to `patterns`), surfaced in `markers`
  // → the classifier's `reasons`.
  patterns: { name: string; re: RegExp }[];
}

// Branded, vendor-specific markers. Ordered by specificity; the FIRST vendor whose
// marker matches wins (Pierre first — its own review is dogfooded through the same
// detector). All matched against the combined review + comment text, case-insensitive.
const FINGERPRINTS: FingerprintDef[] = [
  {
    kind: 'pierre',
    patterns: [{ name: 'Pierre review marker', re: /<!--\s*pierre:claude-review/i }],
  },
  {
    kind: 'coderabbit',
    patterns: [
      { name: 'CodeRabbit summary marker', re: /<!--\s*This is an auto-generated comment: summarize/i },
      { name: 'CodeRabbit walkthrough marker', re: /<!--\s*walkthrough_start\s*-->/i },
      { name: 'Summary by CodeRabbit', re: /Summary by CodeRabbit/i },
    ],
  },
  {
    kind: 'copilot',
    patterns: [{ name: 'Copilot PR overview header', re: /##\s*Pull Request Overview/i }],
  },
  {
    kind: 'qodo',
    patterns: [
      { name: 'Qodo PR Reviewer Guide', re: /PR Reviewer Guide/i },
      { name: 'Qodo PR Review header', re: /##\s*PR Review\b/i },
    ],
  },
  {
    kind: 'sourcery',
    patterns: [{ name: 'Summary by Sourcery', re: /##\s*Summary by Sourcery/i }],
  },
  {
    kind: 'greptile',
    patterns: [
      { name: 'Greptile marker', re: /<!--\s*greptile/i },
      { name: 'Greptile footer', re: /generated by Greptile/i },
    ],
  },
  {
    kind: 'ellipsis',
    patterns: [
      { name: 'Ellipsis marker', re: /<!--\s*ellipsis/i },
      { name: 'Ellipsis banner', re: /reviewed (?:with|by) Ellipsis/i },
    ],
  },
  {
    kind: 'korbit',
    patterns: [
      { name: 'Korbit marker', re: /<!--\s*korbit/i },
      { name: 'Korbit banner', re: /(?:powered by |by )?Korbit AI/i },
    ],
  },
  {
    kind: 'bito',
    patterns: [{ name: 'Bito banner', re: /Code Review by Bito/i }],
  },
];

// Generic AI markers — an in-house tool that carries no brand marker but still reads as
// machine-generated. Matched against the COMBINED text.
const GENERIC_AI_MARKERS: { name: string; re: RegExp }[] = [
  { name: 'AI-generated marker', re: /\bAI[- ]generated\b/i },
  { name: 'generated-by-AI marker', re: /generated by (?:an? )?(?:AI|LLM|bot|agent|model)\b/i },
  { name: 'auto-generated review comment', re: /<!--\s*(?:auto[- ]?generated|bot|ai)[: ]/i },
  { name: 'robot review banner', re: /^\s*🤖\b.*\breview/im },
];

// A uniform severity-tag taxonomy — the tell-tale of a tool that classifies every
// finding by a fixed label set. Requires ≥2 DISTINCT comment bodies each carrying a
// taxonomy token (account-level-ish evidence within a PR's comment set), so a single
// human emoji doesn't misfire. NOTE: branded vendors that ALSO use these tokens (e.g.
// CodeRabbit) are already caught above by their brand marker, so this only fires for an
// UNbranded in-house tool.
const SEVERITY_TAXONOMY: RegExp[] = [
  /⚠️\s*Potential issue/i,
  /🛠️\s*Refactor(?: suggestion)?/i,
  /🧹\s*Nitpick/i,
  />\s*\[!(?:IMPORTANT|WARNING|CAUTION|TIP|NOTE)\]/i,
  /💡\s*(?:Suggestion|Verification)/i,
];

function combine(reviewBody: string | null, commentBodies: string[]): string {
  return [reviewBody, ...commentBodies]
    .filter((s): s is string => typeof s === 'string' && s.length > 0)
    .join('\n');
}

export function fingerprintReview(
  reviewBody: string | null,
  commentBodies: string[],
): ReviewFingerprint {
  const text = combine(reviewBody, commentBodies);
  if (!text) return { marked: false, tool: null, markers: [] };

  // 1. Branded vendor (or Pierre) markers — first match wins.
  for (const def of FINGERPRINTS) {
    const hit = def.patterns.filter((p) => p.re.test(text));
    if (hit.length > 0) {
      return { marked: true, tool: def.kind, markers: hit.map((p) => p.name) };
    }
  }

  // 2. Generic AI markers (no vendor brand).
  const generic = GENERIC_AI_MARKERS.filter((p) => p.re.test(text));
  if (generic.length > 0) {
    return { marked: true, tool: 'in_house', markers: generic.map((p) => p.name) };
  }

  // 3. Uniform severity taxonomy across ≥2 distinct comment bodies.
  const bodiesWithTaxonomy = commentBodies.filter(
    (b) => typeof b === 'string' && SEVERITY_TAXONOMY.some((re) => re.test(b)),
  );
  if (bodiesWithTaxonomy.length >= 2) {
    return {
      marked: true,
      tool: 'in_house',
      markers: ['uniform severity taxonomy across multiple comments'],
    };
  }

  // 4. Plain human body.
  return { marked: false, tool: null, markers: [] };
}
