import { describe, expect, it } from 'vitest';
import { fingerprintReview } from './review-fingerprint.js';

describe('fingerprintReview', () => {
  it("recognises Pierre's own posted-review marker → 'pierre'", () => {
    const fp = fingerprintReview(
      'Nice work overall.\n\n<!-- pierre:claude-review v=1 -->',
      [],
    );
    expect(fp.marked).toBe(true);
    expect(fp.tool).toBe('pierre');
    expect(fp.markers.length).toBeGreaterThan(0);
  });

  it('recognises branded vendor markers → the vendor kind', () => {
    expect(fingerprintReview('Summary by CodeRabbit\n\n- foo', []).tool).toBe('coderabbit');
    expect(
      fingerprintReview('<!-- This is an auto-generated comment: summarize -->', []).tool,
    ).toBe('coderabbit');
    expect(fingerprintReview('## Pull Request Overview\n\nThis PR…', []).tool).toBe('copilot');
    expect(fingerprintReview('PR Reviewer Guide\n\n…', []).tool).toBe('qodo');
    expect(fingerprintReview('## Summary by Sourcery\n\n…', []).tool).toBe('sourcery');
    expect(fingerprintReview('<!-- greptile review -->', []).tool).toBe('greptile');
    expect(fingerprintReview('Reviewed with Ellipsis', []).tool).toBe('ellipsis');
    expect(fingerprintReview('Powered by Korbit AI', []).tool).toBe('korbit');
    expect(fingerprintReview('Code Review by Bito', []).tool).toBe('bito');
  });

  it('finds a branded marker in an inline COMMENT body, not just the review body', () => {
    const fp = fingerprintReview(null, ['Looks good', 'Summary by CodeRabbit\n- x']);
    expect(fp.tool).toBe('coderabbit');
  });

  it("classifies a generic AI marker (no brand) → 'in_house'", () => {
    expect(fingerprintReview('This review was AI-generated.', []).tool).toBe('in_house');
    expect(fingerprintReview('Generated by an AI model.', []).tool).toBe('in_house');
  });

  it("classifies a uniform severity taxonomy across ≥2 comments → 'in_house'", () => {
    const fp = fingerprintReview(null, [
      '⚠️ Potential issue: null deref here',
      '🛠️ Refactor suggestion: extract this',
    ]);
    expect(fp.marked).toBe(true);
    expect(fp.tool).toBe('in_house');
  });

  it('does NOT fire the taxonomy heuristic on a single emoji comment (avoids human FP)', () => {
    const fp = fingerprintReview(null, ['⚠️ Potential issue: this could crash']);
    expect(fp.marked).toBe(false);
    expect(fp.tool).toBeNull();
  });

  it('returns { marked:false, tool:null } for a plain human review', () => {
    const fp = fingerprintReview('LGTM, just fix the typo in the header and ship it.', [
      'can you rename this variable?',
    ]);
    expect(fp).toEqual({ marked: false, tool: null, markers: [] });
  });

  it('returns { marked:false, tool:null } for empty input', () => {
    expect(fingerprintReview(null, [])).toEqual({ marked: false, tool: null, markers: [] });
    expect(fingerprintReview('', [''])).toEqual({ marked: false, tool: null, markers: [] });
  });

  it('prefers a branded vendor over the generic in-house fallback', () => {
    // CodeRabbit uses the same emoji taxonomy, but its brand marker must win.
    const fp = fingerprintReview('Summary by CodeRabbit', [
      '⚠️ Potential issue',
      '🛠️ Refactor suggestion',
    ]);
    expect(fp.tool).toBe('coderabbit');
  });
});
